package application;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class EscenaPrincipalController {
	@FXML
	private Label lblmensaje;

	// Event Listener on Button.onAction
	@FXML
	public void btnAceptar(ActionEvent event) {
		// TODO Autogenerated
		
		lblmensaje.setText("¡Bienvenido!");
	}
}
